services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql-01
    restart: always
    tty: true
    user: postgres
    environment:
      - POSTGRESQL_PASSWORD=test123
    volumes:
      - ${PWD}/postgresql-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-01
    restart: always
    tty: true
    ports:
      - "10001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=amelon@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123
